/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.receptionistrole;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.enterprise.HospitalEnterprise;
import com.neu.business.organization.DoctorOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.patient.Patient;
import com.neu.business.patient.PatientDirectory;
import com.neu.business.useraccount.UserAccount;
import com.neu.business.workqueue.ScheduleAppointmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Soham
 */
public class ScheduleAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleAppointmentJPanel
     */
    private JPanel userProcessContainer;

    private UserAccount userAccount;
    private HospitalEnterprise enterprise;

    public ScheduleAppointmentJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (HospitalEnterprise) enterprise;
        this.userAccount = userAccount;

        populateDoctorComboBox();

        populatePatientComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorNameJComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        patientNameJComboBox = new javax.swing.JComboBox<>();
        scheduleAppointmentJButton = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Schedule Appointment");

        jLabel2.setText("Doctor Name : ");

        jLabel3.setText("Patient Name : ");

        patientNameJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameJComboBoxActionPerformed(evt);
            }
        });

        scheduleAppointmentJButton.setText("Schedule Appointment");
        scheduleAppointmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleAppointmentJButtonActionPerformed(evt);
            }
        });

        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(88, 88, 88)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(patientNameJComboBox, 0, 164, Short.MAX_VALUE)
                                .addComponent(doctorNameJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton2)
                            .addGap(206, 206, 206)
                            .addComponent(scheduleAppointmentJButton))))
                .addContainerGap(417, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(doctorNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patientNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scheduleAppointmentJButton)
                    .addComponent(backJButton2))
                .addContainerGap(347, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3});

    }// </editor-fold>//GEN-END:initComponents

    private void scheduleAppointmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleAppointmentJButtonActionPerformed
        // TODO add your handling code here:
        String message = patientNameJComboBox.getSelectedItem().toString() + " is scheduled for visit";

        ScheduleAppointmentWorkRequest appointmentWorkRequest = new ScheduleAppointmentWorkRequest();
        appointmentWorkRequest.setMessage(message);
        appointmentWorkRequest.setSender(userAccount);
        appointmentWorkRequest.setStatus("Scheduled for visit");
        appointmentWorkRequest.setPatient((Patient) patientNameJComboBox.getSelectedItem());

        Organization doctorOrganization = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DoctorOrganization) {
                doctorOrganization = organization;
                break;
            }
        }
        if (doctorOrganization != null) {
            doctorOrganization.getWorkQueue().getWorkRequestList().add(appointmentWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(appointmentWorkRequest);
            for (UserAccount account : doctorOrganization.getUserAccountDirectory().getUserAccountList()) {
                if (account.getEmployee().getName().equals(doctorNameJComboBox.getSelectedItem().toString())) {
                    account.getWorkQueue().getWorkRequestList().add(appointmentWorkRequest);
                    appointmentWorkRequest.setReceiver(account);

                }
            }
        }
        JOptionPane.showMessageDialog(null, "Appointment scheduled!");

    }//GEN-LAST:event_scheduleAppointmentJButtonActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        com.neu.userinterface.receptionistrole.ReceptionistWorkAreaJPanel receptionistwjp = (ReceptionistWorkAreaJPanel) component;
        receptionistwjp.populateAppointentsTable(enterprise);;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void populatePatientComboBox() {
        patientNameJComboBox.removeAllItems();

        PatientDirectory patientDirectory = enterprise.getPatientDirectory();
        for (Patient patient : patientDirectory.getPatientList()) {
            patientNameJComboBox.addItem(patient);
        }
    }

    private void populateDoctorComboBox() {
        doctorNameJComboBox.removeAllItems();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DoctorOrganization) {
                for (UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList()) {
                    doctorNameJComboBox.addItem(userAccount.getEmployee().getName());
                }
            }
        }
    }

    private void patientNameJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JComboBox<String> doctorNameJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<Object> patientNameJComboBox;
    private javax.swing.JButton scheduleAppointmentJButton;
    // End of variables declaration//GEN-END:variables

}
