/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.chemistrole;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.enterprise.PharmacyEnterprise;
import com.neu.business.network.Network;
import com.neu.business.organization.ChemistOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.patient.Prescription;
import com.neu.business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anmol
 */
public class ManageStockJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStockJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private ChemistOrganization chemistOrganization;
    private ArrayList<Prescription> prescriptionList;

    public ManageStockJPanel(JPanel userProcessContainer, ChemistOrganization chemistOrganization, ArrayList<Prescription> prescriptionList, UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.network = network;
        this.chemistOrganization = chemistOrganization;
        this.prescriptionList = prescriptionList;

        populateFields();
    }

    public void populateFields() {
        txtFieldCurrentStock.setText(String.valueOf(chemistOrganization.getStock()));
        txtFieldNewStock.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldCurrentStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldNewStock = new javax.swing.JTextField();
        btnUpdateStock = new javax.swing.JButton();
        btnOrderOpioids = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Stock");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jLabel2.setText("Current Stock :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 76, -1, -1));

        txtFieldCurrentStock.setEditable(false);
        add(txtFieldCurrentStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 73, 189, -1));

        jLabel3.setText("New Stock :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 147, -1, -1));
        add(txtFieldNewStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 144, 189, -1));

        btnUpdateStock.setText("Update Stock");
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });
        add(btnUpdateStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 228, -1, -1));

        btnOrderOpioids.setText("Order Opioids");
        btnOrderOpioids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderOpioidsActionPerformed(evt);
            }
        });
        add(btnOrderOpioids, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 228, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 228, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderOpioidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderOpioidsActionPerformed
        // TODO add your handling code here:

        //        Network currentNetwork;
        //        PharmaceuticalCompanyEnterprise pharmaEnterprise = new PharmaceuticalCompanyEnterprise("Pharmaceutical Company Enterprise");
        //
        //        for(Network network : system.getNetworkList())
        //        {
        //            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList())
        //            {
        //                if(e.getName().equals(enterprise.getName()))
        //                {
        //                    currentNetwork = network;// getting which network the current chemist and pharmaceutical company are in
        //
        //                    if(e instanceof PharmaceuticalCompanyEnterprise)
        //                        pharmaEnterprise = (PharmaceuticalCompanyEnterprise) e;
        //                    OrderOpioidsJPanel orderOpioidsJPanel = new OrderOpioidsJPanel(userProcessContainer, pharmaEnterprise, enterprise, organization, currentNetwork, userAccount);
        //                    userProcessContainer.add("OrderOpioidsJPanel", orderOpioidsJPanel);
        //                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //                    layout.next(userProcessContainer);
        //                }
        //            }
        //        }
        OrderOpioidsJPanel orderOpioidsJPanel = new OrderOpioidsJPanel(userProcessContainer, network, chemistOrganization, userAccount);
        userProcessContainer.add("OrderOpioidsJPanel", orderOpioidsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();

        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrderOpioidsActionPerformed

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
        // TODO add your handling code here:
        int newStock = Integer.parseInt(txtFieldNewStock.getText());
        int oldStock = chemistOrganization.getStock();
        if (newStock > oldStock) {
            JOptionPane.showMessageDialog(null, "New stock shouldn't be more than old stock", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        chemistOrganization.setStock(newStock);
        ArrayList<String> stockChangesHistory = chemistOrganization.getStockChangeHistory();
        String stockChange = "";
        stockChange = "Stock changed from " + String.valueOf(oldStock) + " to " + String.valueOf(newStock);
        stockChangesHistory.add(stockChange);
        chemistOrganization.setStockChangeHistory(stockChangesHistory);
        JOptionPane.showMessageDialog(null, chemistOrganization + "'s current stock has been updated to " + chemistOrganization.getStock());
        populateFields();
//        txtFieldCurrentStock.setText(String.valueOf(newStock));
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnOrderOpioids;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFieldCurrentStock;
    private javax.swing.JTextField txtFieldNewStock;
    // End of variables declaration//GEN-END:variables
}
