/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.chemistrole;

import com.neu.business.organization.ChemistOrganization;
import com.neu.business.patient.Prescription;
import com.neu.userinterface.receptionistrole.ReceptionistWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anmol
 */
public class SellOpioidsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellOpioidsJPanel
     */
    private JPanel userProcessContainer;
    private ChemistOrganization chemistOrganization;
    private ArrayList<Prescription> prescriptionList;

    public SellOpioidsJPanel(JPanel userProcessContainer, ChemistOrganization chemistOrganization, ArrayList<Prescription> prescriptionList) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.chemistOrganization = chemistOrganization;
        this.prescriptionList = prescriptionList;

        populatePrescriptionTable();
        populateSoldOpioidsTable();
    }

    public void populatePrescriptionTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblPrescriptions.getModel();
        dtm.setRowCount(0);
        int count = 1;
        for (Prescription prescription : prescriptionList) {
            if (prescription.isFulfilled() == false) {
                Object[] row = new Object[4];
                row[0] = count++;
                row[1] = prescription.getPatientName();
                row[2] = prescription;
                row[3] = prescription.getTotalOpioidsPrescribed();

                dtm.addRow(row);
            }
        }
    }

    public void populateSoldOpioidsTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSold.getModel();
        dtm.setRowCount(0);
        int count = 1;
        for (Prescription prescription : prescriptionList) {
            if (prescription.isFulfilled() == true && prescription.getChemistName().equals(chemistOrganization.getName())) {
                Object[] row = new Object[5];
                row[0] = count++;
                row[1] = prescription.getPatientName();
                row[2] = prescription;
                row[3] = prescription.getTotalOpioidsPrescribed();
                row[4] = prescription.getDateOfFulfilment();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrescriptions = new javax.swing.JTable();
        btnSell = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSold = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPrescriptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Patient Name", "Doctor Name", "Opioids Prescribed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrescriptions);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 720, 329));

        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 692, -1, -1));

        tblSold.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Patient Name", "Doctor Name", "Opioids Sold", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSold);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 720, 329));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sell Opioids");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 16, -1, -1));

        jLabel3.setText("Pending prescriptions :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel4.setText("Fulfilled prescriptions :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblPrescriptions.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select an order to fulfil", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Prescription prescription = (Prescription) tblPrescriptions.getValueAt(selectedRow, 2);
        prescription.setDateOfFulfilment(new Date());
        prescription.setChemistName(chemistOrganization.getName());
        prescription.setFulfilled(true);
        int oldStock = chemistOrganization.getStock();
        int stockSold = prescription.getTotalOpioidsPrescribed();
        int newStock = oldStock - stockSold;
        chemistOrganization.setStock(newStock);
        chemistOrganization.addOrderSoldPrescription(prescription);
        
        JOptionPane.showMessageDialog(null, prescription.getPatientName() + "'s prescription of " + prescription.getTotalOpioidsPrescribed() + " opioids fulfilled");
        populatePrescriptionTable();
        populateSoldOpioidsTable();

    }//GEN-LAST:event_btnSellActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        com.neu.userinterface.chemistrole.ChemistWorkAreaJPanel chemistwjp = (ChemistWorkAreaJPanel) component;
        chemistwjp.populateInitialStock();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPrescriptions;
    private javax.swing.JTable tblSold;
    // End of variables declaration//GEN-END:variables
}
