/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.dearole;

import com.neu.business.enterprise.DrugEnforcementAdministrationEnterprise;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.enterprise.PharmacyEnterprise;
import com.neu.business.network.Network;
import com.neu.business.organization.ChemistOrganization;
import com.neu.business.organization.DEAOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author shrikantmudholkar
 */
public class DEAWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form deaWorkArea
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private DEAOrganization organization;
    private UserAccount account;
    private Network network;

    public DEAWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DEAOrganization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.account = account;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPharmacyReport = new javax.swing.JButton();
        btnDoctorReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DEA Agent's work area");

        btnPharmacyReport.setText("Generate Pharmacy Report");
        btnPharmacyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmacyReportActionPerformed(evt);
            }
        });

        btnDoctorReport.setText("Generate Doctor Report");
        btnDoctorReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnPharmacyReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctorReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(604, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(btnPharmacyReport)
                .addGap(77, 77, 77)
                .addComponent(btnDoctorReport)
                .addContainerGap(475, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPharmacyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyReportActionPerformed
        // TODO add your handling code here:

//        Map<ChemistOrganization, Double> discripancyMap = new HashMap<>();
//        Double discripancy = 0.0;
//
//        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//
//            if (enterprise instanceof PharmacyEnterprise) {
//                for (Organization chemistOrganization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//                    if (chemistOrganization instanceof ChemistOrganization) {
//                        discripancy = network.pharmacyStockDiscrepancy((ChemistOrganization) chemistOrganization);
//                        discripancyMap.put((ChemistOrganization) chemistOrganization, discripancy);
//                    }
//                }
//            }
//        }

        DiscrepancyJPanel discrepancyJPanel = new DiscrepancyJPanel(userProcessContainer, network);
        userProcessContainer.add("DiscrepancyJPanel", discrepancyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPharmacyReportActionPerformed

    private void btnDoctorReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctorReport;
    private javax.swing.JButton btnPharmacyReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
