/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.pharmaceuticalcompanymanagerrole;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.organization.PharmaceuticalCompanyManagerOrganization;
import com.neu.business.useraccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author shrikantmudholkar
 */
public class PharmaceuticalCompanyManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form pharmaceuticalCompanyManagerWA
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private PharmaceuticalCompanyManagerOrganization organization;
    private Enterprise enterprise;
    
    public PharmaceuticalCompanyManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PharmaceuticalCompanyManagerOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Pharma Company Manager Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(668, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(571, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
