/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.pharmaceuticalcompanymanagerrole;

import com.neu.business.enterprise.PharmaceuticalCompanyEnterprise;
import com.neu.business.organization.PharmaceuticalCompanyManagerOrganization;
import com.neu.business.useraccount.UserAccount;
import com.neu.business.workqueue.PharmacySupplyWorkRequest;
import com.neu.business.workqueue.WorkQueue;
import com.neu.business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrikantmudholkar
 */
public class PharmaceuticalCompanyManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form pharmaceuticalCompanyManagerWA
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private PharmaceuticalCompanyManagerOrganization organization;
    private PharmaceuticalCompanyEnterprise enterprise;

    public PharmaceuticalCompanyManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, PharmaceuticalCompanyManagerOrganization organization, PharmaceuticalCompanyEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;

        populateOrdersTable();
        txtFieldRemainingStock.setText(String.valueOf((enterprise).getStock()));
    }

    public void populateOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();

        model.setRowCount(0);
        int count = 0;

        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = count++;
            row[1] = ((PharmacySupplyWorkRequest) workRequest).getRequesterName();
            row[2] = ((PharmacySupplyWorkRequest) workRequest).getOrderAmount();
            row[3] = workRequest.getRequestDate();
            row[4] = workRequest;

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingOrders = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFieldRemainingStock = new javax.swing.JTextField();
        btnAddStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRespond = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblPendingOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pharmacy Name", "Opioids Requested", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendingOrders);
        if (tblPendingOrders.getColumnModel().getColumnCount() > 0) {
            tblPendingOrders.getColumnModel().getColumn(0).setResizable(false);
            tblPendingOrders.getColumnModel().getColumn(1).setResizable(false);
            tblPendingOrders.getColumnModel().getColumn(2).setResizable(false);
            tblPendingOrders.getColumnModel().getColumn(3).setResizable(false);
            tblPendingOrders.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("Remaining Stock :");

        txtFieldRemainingStock.setEditable(false);

        btnAddStock.setText("Add to stock");

        jLabel1.setText("Pending distribution orders :");

        btnRespond.setText("Respond to Order");
        btnRespond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespondActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Pharmaceutical Company Manager Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRespond)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtFieldRemainingStock, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(101, 101, 101)
                                    .addComponent(btnAddStock)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldRemainingStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStock))
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRespond)
                .addContainerGap(400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespondActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblPendingOrders.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select an order to fulfil", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PharmacySupplyWorkRequest request = (PharmacySupplyWorkRequest) tblPendingOrders.getValueAt(selectedRow, 4);

        if (request.getStatus().equals("Order Completed")) {
            JOptionPane.showMessageDialog(null, "Order already completed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setStatus("Processing");

        SupplyOpioidsJPanel supplyOpioidsJPanel = new SupplyOpioidsJPanel(userProcessContainer, request, enterprise);
        userProcessContainer.add("supplyOpioidsJPanel", supplyOpioidsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnRespondActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnRespond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendingOrders;
    private javax.swing.JTextField txtFieldRemainingStock;
    // End of variables declaration//GEN-END:variables
}
