/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.pharmaceuticalcompanymanagerrole;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.enterprise.PharmaceuticalCompanyEnterprise;
import com.neu.business.enterprise.PharmacyEnterprise;
import com.neu.business.organization.ChemistOrganization;
import com.neu.business.workqueue.PharmacySupplyWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anmol
 */
public class SupplyOpioidsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplyOpioidsJPanel
     */
    private JPanel userProcessContainer;
    private PharmacySupplyWorkRequest pharmaWorkRequest;
    private PharmaceuticalCompanyEnterprise enterprise;

    public SupplyOpioidsJPanel(JPanel userProcessContainer, PharmacySupplyWorkRequest pharmaWorkRequest, PharmaceuticalCompanyEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmaWorkRequest = pharmaWorkRequest;
        this.enterprise = enterprise;

        populateFields();
    }

    public void populateFields() {
        txtFieldPharmacyName.setText(pharmaWorkRequest.getRequesterName());
        txtFieldOrderAmount.setText(String.valueOf(pharmaWorkRequest.getOrderAmount()));
        txtFieldStockLeft.setText(String.valueOf((enterprise).getStock()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldPharmacyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldOrderAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldStockLeft = new javax.swing.JTextField();
        btnDispatch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Pharmacy Name :");

        jLabel2.setText("Order Amount :");

        jLabel3.setText("Stock Remaining :");

        txtFieldStockLeft.setEnabled(false);

        btnDispatch.setText("Dispatch Opioids");
        btnDispatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispatchActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(btnDispatch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldPharmacyName)
                            .addComponent(txtFieldOrderAmount)
                            .addComponent(txtFieldStockLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFieldStockLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldPharmacyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFieldOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(btnDispatch)
                .addGap(83, 83, 83)
                .addComponent(btnBack)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDispatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispatchActionPerformed
        // TODO add your handling code here:

        int stockLeft = Integer.parseInt(txtFieldStockLeft.getText());
        int orderAmount = Integer.parseInt(txtFieldOrderAmount.getText());

        if (stockLeft < orderAmount) {
            JOptionPane.showMessageDialog(null, "You do not have enough stock to complete this order", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            enterprise.setStock(stockLeft - orderAmount);
            // PharmacyEnterprise pharmacyEnterpise = pharmaWorkRequest.getPharmacyEnterprise();
            // ChemistOrganization organization = (ChemistOrganization)enterprise.getOrganizationDirectory().getOrganizationList().get(0);
            //int chemistStock = organization.getStock();
            //organization.setStock(chemistStock+orderAmount);
            pharmaWorkRequest.setResolveDate(new Date());
            pharmaWorkRequest.setStatus("Order Completed");

            Object[] options = {"OK"};
            int n = JOptionPane.showOptionDialog(null,
                    "Opioids supplied", "Title",
                    JOptionPane.PLAIN_MESSAGE,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]);

            txtFieldStockLeft.setText(String.valueOf((enterprise).getStock()));

        }

    }//GEN-LAST:event_btnDispatchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDispatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFieldOrderAmount;
    private javax.swing.JTextField txtFieldPharmacyName;
    private javax.swing.JTextField txtFieldStockLeft;
    // End of variables declaration//GEN-END:variables
}
