/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.pharmaceuticalcompanymanagerrole;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.enterprise.PharmaceuticalCompanyEnterprise;
import com.neu.business.enterprise.PharmacyEnterprise;
import com.neu.business.organization.ChemistOrganization;
import com.neu.business.workqueue.PharmacySupplyWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anmol
 */
public class SupplyOpioidsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplyOpioidsJPanel
     */
    private JPanel userProcessContainer;
    private PharmacySupplyWorkRequest pharmaWorkRequest;
    private PharmaceuticalCompanyEnterprise enterprise;

    public SupplyOpioidsJPanel(JPanel userProcessContainer, PharmacySupplyWorkRequest pharmaWorkRequest, PharmaceuticalCompanyEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmaWorkRequest = pharmaWorkRequest;
        this.enterprise = enterprise;

        populateFields();
    }

    public void populateFields() {
        txtFieldPharmacyName.setText(pharmaWorkRequest.getRequesterName());
        txtFieldOrderAmount.setText(String.valueOf(pharmaWorkRequest.getOrderAmount()));
        txtFieldStockLeft.setText(String.valueOf((enterprise).getStock()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldPharmacyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldOrderAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldStockLeft = new javax.swing.JTextField();
        btnDispatch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pharmacy Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 146, -1, -1));
        add(txtFieldPharmacyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 143, 200, -1));

        jLabel2.setText("Order Amount :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 193, -1, -1));
        add(txtFieldOrderAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 187, 200, -1));

        jLabel3.setText("Stock Remaining :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 102, -1, -1));

        txtFieldStockLeft.setEnabled(false);
        add(txtFieldStockLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 99, 200, -1));

        btnDispatch.setText("Dispatch Opioids");
        btnDispatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispatchActionPerformed(evt);
            }
        });
        add(btnDispatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 247, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 359, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Dispatch Opioids");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 16, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDispatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispatchActionPerformed
        // TODO add your handling code here:

        int stockLeft = Integer.parseInt(txtFieldStockLeft.getText());
        int orderAmount = Integer.parseInt(txtFieldOrderAmount.getText());

        if (stockLeft < orderAmount) {
            JOptionPane.showMessageDialog(null, "You do not have enough stock to complete this order", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            enterprise.setStock(stockLeft - orderAmount);

            pharmaWorkRequest.setResolveDate(new Date());
            pharmaWorkRequest.setStatus("Order Completed");

            JOptionPane.showMessageDialog(null, "Order of " + pharmaWorkRequest.getOrderAmount() + " dispatched to " + pharmaWorkRequest.getRequesterName());
            txtFieldStockLeft.setText(String.valueOf((enterprise).getStock()));
        }

    }//GEN-LAST:event_btnDispatchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDispatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFieldOrderAmount;
    private javax.swing.JTextField txtFieldPharmacyName;
    private javax.swing.JTextField txtFieldStockLeft;
    // End of variables declaration//GEN-END:variables
}
