/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.adminrole.hospital;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.enterprise.CommunityRehabEnterprise;
import com.neu.business.enterprise.HospitalEnterprise;
import com.neu.business.network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Soham
 */
public class ManageHospitalRehabAssociationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalRehabAssociationJPanel
     */
    private JPanel userProcessContainer;
    private HospitalEnterprise enterprise;
    private Network network;

    public ManageHospitalRehabAssociationJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (HospitalEnterprise) enterprise;
        this.network = network;
        populateRehabComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        comboBoxRehab = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnAssociateRehabAction = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Rehabilitation Assoiation");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Rehabilitation Facility :");

        btnAssociateRehabAction.setText("Confirm Association");
        btnAssociateRehabAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociateRehabActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssociateRehabAction)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(backJButton)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(jLabel2)
                            .addGap(103, 103, 103)
                            .addComponent(comboBoxRehab, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRehab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addComponent(btnAssociateRehabAction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateRehabComboBox() {
        comboBoxRehab.removeAllItems();
        network.getEnterpriseDirectory().getEnterpriseList().stream()
                .filter((e) -> (e.getEnterpriseType().getValue().equals("Community Rehab Enterprise")))
                .forEach((e) -> {
                    comboBoxRehab.addItem(e.getName());
                });
    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAssociateRehabActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociateRehabActionActionPerformed
        // TODO add your handling code here:

        CommunityRehabEnterprise commRehabEnterprise = (CommunityRehabEnterprise) network.getEnterpriseByName((String) comboBoxRehab.getSelectedItem());

        if (commRehabEnterprise == null) {
            JOptionPane.showMessageDialog(null, "Select a Rehabilitation");
            return;
        }

        for (CommunityRehabEnterprise en : enterprise.getAssociatedCommRehabList()) {
            if (en.equals(commRehabEnterprise)) {
                JOptionPane.showMessageDialog(null, "Already associated with this rehab");
            }
            return;
        }
        enterprise.addAssociatedRehabilitation(commRehabEnterprise);
        JOptionPane.showMessageDialog(null, enterprise.getName() + " is now associated with " + commRehabEnterprise.getName());
    }//GEN-LAST:event_btnAssociateRehabActionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAssociateRehabAction;
    private javax.swing.JComboBox comboBoxRehab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
