/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.doctorrole;

import com.neu.business.enterprise.Enterprise;
import com.neu.business.network.Network;
import com.neu.business.organization.DoctorOrganization;
import com.neu.business.patient.Patient;
import com.neu.business.patient.PatientDirectory;
import com.neu.business.useraccount.UserAccount;
import com.neu.business.workqueue.ScheduleAppointmentWorkRequest;
import com.neu.business.workqueue.SendToRehabilitationWorkRequest;
import com.neu.business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrikantmudholkar
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientDirectory patientDirectory;
    private Network network;
    private ArrayList<Patient> doctorRecommendations;

    /**
     * Creates new form doctorWorkArea
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, DoctorOrganization doctorOrganization, Enterprise enterprise, Network network, PatientDirectory patientDirectory) {
        initComponents();
        this.patientDirectory = patientDirectory;
        this.userProcessContainer = userProcessContainer;
        this.doctorOrganization = doctorOrganization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageAddictedPatients = new javax.swing.JButton();
        btnDiagnosePatients = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Doctor Work Area");

        btnManageAddictedPatients.setText("Manage Addicted Patients");
        btnManageAddictedPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAddictedPatientsActionPerformed(evt);
            }
        });

        btnDiagnosePatients.setText("Diagnose Patients");
        btnDiagnosePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosePatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageAddictedPatients)
                        .addGap(141, 141, 141)
                        .addComponent(btnDiagnosePatients)))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageAddictedPatients)
                    .addComponent(btnDiagnosePatients))
                .addContainerGap(545, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosePatientsActionPerformed
        // TODO add your handling code here:
        ManageScheduleJPanel manageScheduleJPanel = new ManageScheduleJPanel(userProcessContainer, userAccount, doctorOrganization, enterprise, patientDirectory, network);
        userProcessContainer.add("manageScheduleJPanel", manageScheduleJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDiagnosePatientsActionPerformed

    private void btnManageAddictedPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAddictedPatientsActionPerformed

        RehabAssociationJPanel rehabAssociationJPanel = new RehabAssociationJPanel(userProcessContainer, network, userAccount, doctorOrganization, enterprise);
        userProcessContainer.add("RehabAssociationJPanel", rehabAssociationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAddictedPatientsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnosePatients;
    private javax.swing.JButton btnManageAddictedPatients;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
