/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.doctorrole;

import com.neu.business.enterprise.CommunityRehabEnterprise;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.network.Network;
import com.neu.business.organization.DoctorOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.organization.RehabilitationManagerOrganization;
import com.neu.business.patient.Patient;
import com.neu.business.useraccount.UserAccount;
import com.neu.business.workqueue.SendToRehabilitationWorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author Soham
 */
public class RehabAssociationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RehabAssociationJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private Network network;
    private DoctorOrganization doctorOrganization;
    private UserAccount userAccount;

    public RehabAssociationJPanel(JPanel userProcessContainer, Network network, DoctorOrganization doctorOrganization, Patient patient, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.network = network;
        this.doctorOrganization = doctorOrganization;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSendToRehab = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOpioidAddictedPatients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSendToRehab.setText("Send to Rehabilitation");
        btnSendToRehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToRehabActionPerformed(evt);
            }
        });

        tblOpioidAddictedPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Opioid Addiction Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOpioidAddictedPatients);

        jLabel1.setText("Opioids Addicted Patients :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSendToRehab)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSendToRehab)
                .addGap(157, 157, 157))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendToRehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToRehabActionPerformed
        // TODO add your handling code here:

        Enterprise commRehabEnterprise = null;
        Organization rehabilitationCompanyManagerOrganization = null;

        SendToRehabilitationWorkRequest sendToRehabilitationWorkRequest = new SendToRehabilitationWorkRequest();
        sendToRehabilitationWorkRequest.setStatus("Rehab needed");
        sendToRehabilitationWorkRequest.setSender(userAccount);
        sendToRehabilitationWorkRequest.setPatient(patient);

        userAccount.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);
        doctorOrganization.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CommunityRehabEnterprise) {
                commRehabEnterprise = enterprise;
                break;
            }

        }

        for (Organization organization : commRehabEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof RehabilitationManagerOrganization) {
                rehabilitationCompanyManagerOrganization = organization;
                break;
            }
        }

        if (rehabilitationCompanyManagerOrganization != null) {
            rehabilitationCompanyManagerOrganization.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);
            for (UserAccount account : rehabilitationCompanyManagerOrganization.getUserAccountDirectory().getUserAccountList()) {
                {
                    account.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);
                    sendToRehabilitationWorkRequest.setReceiver(account);

                }
            }
        }
    }//GEN-LAST:event_btnSendToRehabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendToRehab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblOpioidAddictedPatients;
    // End of variables declaration//GEN-END:variables
}
