/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.doctorrole;

import com.neu.business.enterprise.CommunityRehabEnterprise;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.network.Network;
import com.neu.business.organization.DoctorOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.organization.RehabilitationManagerOrganization;
import com.neu.business.patient.Patient;
import com.neu.business.useraccount.UserAccount;
import com.neu.business.workqueue.SendToRehabilitationWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Soham
 */
public class RehabAssociationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RehabAssociationJPanel
     */
    private JPanel userProcessContainer;
    private Network network;
    private DoctorOrganization doctorOrganization;
    private UserAccount doctorUserAccount;
    private ArrayList<Patient> doctorRecommendations;

    public RehabAssociationJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount, DoctorOrganization doctorOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.doctorOrganization = doctorOrganization;
        this.doctorUserAccount = userAccount;

        populateRehabsComboBox();
        populateAddictedPatientsTable();
    }

    public void populateRehabsComboBox() {
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CommunityRehabEnterprise) {
                comboBoxRehabCenters.addItem(enterprise.getName());
            }
        }
    }

    public void populateAddictedPatientsTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblOpioidAddictedPatients.getModel();
        dtm.setRowCount(0);

        doctorRecommendations = doctorOrganization.getDoctorRecommendations();

        for (Patient patient : doctorRecommendations) {
            Object[] row = new Object[2];
            row[0] = patient;
            row[1] = patient.getRehabStatus();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSendToRehab = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOpioidAddictedPatients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        comboBoxRehabCenters = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSendToRehab.setText("Send to Rehabilitation");
        btnSendToRehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToRehabActionPerformed(evt);
            }
        });

        tblOpioidAddictedPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Opioid Addiction Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOpioidAddictedPatients);

        jLabel1.setText("Opioids Addicted Patients :");

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select rehabilitation center :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(comboBoxRehabCenters, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(btnSendToRehab))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendToRehab)
                    .addComponent(comboBoxRehabCenters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(backJButton1)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendToRehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToRehabActionPerformed
        // TODO add your handling code here:

        Enterprise commRehabEnterprise = null;
        Organization rehabilitationCompanyManagerOrganization = null;

        Patient patient = (Patient) tblOpioidAddictedPatients.getValueAt(tblOpioidAddictedPatients.getSelectedRow(), 0);

        SendToRehabilitationWorkRequest sendToRehabilitationWorkRequest = new SendToRehabilitationWorkRequest();
        sendToRehabilitationWorkRequest.setStatus("Sent to rehab");
        sendToRehabilitationWorkRequest.setSender(doctorUserAccount);
        sendToRehabilitationWorkRequest.setPatient(patient);

        doctorUserAccount.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);
        doctorOrganization.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);

        commRehabEnterprise = (CommunityRehabEnterprise) network.getEnterpriseByName((String) comboBoxRehabCenters.getSelectedItem());

        for (Organization organization : commRehabEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof RehabilitationManagerOrganization) {
                rehabilitationCompanyManagerOrganization = organization;
                break;
            }
        }

        if (rehabilitationCompanyManagerOrganization != null) {
            rehabilitationCompanyManagerOrganization.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);

            for (UserAccount rehabManagerAccount : rehabilitationCompanyManagerOrganization.getUserAccountDirectory().getUserAccountList()) {
                {
                    rehabManagerAccount.getWorkQueue().getWorkRequestList().add(sendToRehabilitationWorkRequest);
                    sendToRehabilitationWorkRequest.setReceiver(rehabManagerAccount);

                }
            }
        }

        JOptionPane.showMessageDialog(null, patient.getName() + " sent to " + commRehabEnterprise.getName());
    }//GEN-LAST:event_btnSendToRehabActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton btnSendToRehab;
    private javax.swing.JComboBox<Object> comboBoxRehabCenters;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblOpioidAddictedPatients;
    // End of variables declaration//GEN-END:variables
}
